
name: CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Create Wheel
      run: |
          pip install wheel
          python setup.py sdist bdist_wheel
          mkdir wheelhouse
          cp dist/spyrit-* wheelhouse/
          ls wheelhouse
          rm -r dist
          mv wheelhouse dist
    - name: Upload wheels
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/

  test_install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Cache
      id: cache_data_example
      uses: actions/cache@v2
      with:
        path: data_example
        key: data_example3
        restore-keys: data_example3
    - name: Run the ISBI test on Mac and Linux
      if: matrix.os != 'windows-latest'
      run: |
          mkdir -p data_example
          pip install -e .
          cd data_example
          if [ -f "data/stl10_binary.tar.gz" ]; then
              cd data
              tar xzvf stl10_binary.tar.gz
              cd ..
          fi
          python ../.github/workflows/example_2020_ISBI.py
          rm -rf data/stl10_binary
    - name: Run the Optic test on Mac and Linux
      if: matrix.os != 'windows-latest'
      run: |
          mkdir -p data_example
          pip install -e .
          pip install tabulate pylops bm3d
          cd data_example
          wget https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/expe.zip
          unzip expe.zip
          wget https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/model.zip
          unzip model.zip
          cd ..
          python .github/workflows/example_2021_OpticsExpress.py
          cd data_example
          rm -rf expe.zip model.zip expe_2 model
    - name: Run the ISBI test on Windows
      if: matrix.os == 'windows-latest'
      run: |
          if(-not (Test-Path -path "data_example")) { mkdir data_example }
          pip install requests torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install -e .
          cd data_example
          if(Test-Path -path "data\stl10_binary.tar.gz") {
              cd data
              tar xzvf stl10_binary.tar.gz
              cd ..
          }
          python ..\.github\workflows\example_2020_ISBI.py
          rm -r -fo data/stl10_binary
    - name: Run the Optic test on Windows
      if: matrix.os == 'windows-latest'
      run: |
          if(-not (Test-Path -path "data_example")) { mkdir data_example }
          pip install requests torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install -e .
          pip install tabulate pylops bm3d
          cd data_example
          C:\msys64\usr\bin\wget.exe https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/expe.zip
          unzip expe.zip
          C:\msys64\usr\bin\wget.exe https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/model.zip
          unzip model.zip
          cd ..
          python .github\workflows\example_2021_OpticsExpress.py
          cd data_example
          rm -r -fo expe.zip model.zip expe_2 model

  test_wheel:
    runs-on: ${{ matrix.os }}
    needs: [build_wheel]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Cache
      id: cache_data_example
      uses: actions/cache@v2
      with:
        path: data_example
        key: data_example3
        restore-keys: data_example3
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist/
    - name: Run the ISBI test on Mac and Linux
      if: matrix.os != 'windows-latest'
      run: |
          mkdir -p data_example
          cd dist
          pip install spyrit-*.whl
          pip install tabulate pylops bm3d
          cd ../data_example
          if [ -f "data/stl10_binary.tar.gz" ]; then
              cd data
              tar xzvf stl10_binary.tar.gz
              cd ..
          fi
          python ../.github/workflows/example_2020_ISBI.py
          rm -rf data/stl10_binary
    - name: Run the Optic test on Mac and Linux
      if: matrix.os != 'windows-latest'
      run: |
          mkdir -p data_example
          cd dist
          pip install spyrit-*.whl
          pip install tabulate pylops bm3d
          cd ../data_example
          wget https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/expe.zip
          unzip expe.zip
          wget https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/model.zip
          unzip model.zip
          cd ..
          python .github/workflows/example_2021_OpticsExpress.py
          cd data_example
          rm -rf expe.zip model.zip expe_2 model
    - name: Run the ISBI test on Windows
      if: matrix.os == 'windows-latest'
      run: |
          if(-not (Test-Path -path "data_example")) { mkdir data_example }
          cd dist
          pip install requests torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install --find-links=. spyrit
          cd ..\data_example
          if(Test-Path -path "data\stl10_binary.tar.gz") {
              cd data
              tar xzvf stl10_binary.tar.gz
              cd ..
          }
          python ..\.github\workflows\example_2020_ISBI.py
          rm -r -fo data/stl10_binary
    - name: Run the Optic test on Windows
      if: matrix.os == 'windows-latest'
      run: |
          if(-not (Test-Path -path "data_example")) { mkdir data_example }
          cd dist
          pip install requests torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install tabulate pylops bm3d
          pip install --find-links=. spyrit
          cd ..\data_example
          C:\msys64\usr\bin\wget.exe https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/expe.zip
          unzip expe.zip
          C:\msys64\usr\bin\wget.exe https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/model.zip
          unzip model.zip
          cd ..
          python .github\workflows\example_2021_OpticsExpress.py
          cd data_example
          rm -r -fo expe.zip model.zip expe_2 model

  publish_wheel:
    runs-on: ubuntu-latest
    needs: [build_wheel, test_wheel, test_install]
    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - uses: actions/download-artifact@v1
      with:
        name: dist
        path: dist/
    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI }}
        skip_existing: true

